#!/usr/bin/env zsh
# gitignore-defaults.zsh
# Reusable default .gitignore patterns
# Loaded by git-genignore and other helpers

typeset -ga GITIGNORE_DEFAULTS GSUBIGNORE_DEFAULTS

GITIGNORE_DEFAULTS=(
    "# User directories at user level"
    "Documents/"
    "Downloads/"
    "Applications/"
    "Music/"
    "Movies/"
    "Pictures/"
    "Library/"
    "raycast/"
    ".git/"
    "plugins/"
    "logs/"
    ".zsh_*/"
    ".zcomp*/"
    "save/"
    "old*/"
    ".claude/"
    "claude/"
    "cat"
    "glab-cli/"
    "gh/"
    ""

    "# OS generated files"
    ".DS_Store"
    ".DS_Store?"
    "._*"
    ".Spotlight-V100"
    ".Trashes"
    "ehthumbs.db"
    "Thumbs.db"
    ""

    "# Backups and Archives"
    "*.bak"
    "*.zip"
    "*.backup"
    "*.arc"
    "*.archive"
    "*.old"
    "*.save"
    ".*.bak"
    ".*.old"
    ".*.backup"
    ".*.arc"
    ".*.archive"
    ".*.save"
    "backup/"
    "archive/"
    "backups/"
    "archives/"
    "old*"
    "old.*"
    "old-*"
    "save/"
    ""

    "# Editor directories and files"
    ".idea/"
    ".vscode/"
    "*.swp"
    "*.swo"
    "*~"
    ""

    "# Logs and databases"
    "*.log"
    "logs/"
    "log/"
    "*.sql"
    "*.sqlite"
    ""

    "# Dependencies and build artifacts"
    "node_modules/"
    "dist/"
    "build/"
    "*.pyc"
    "__pycache__/"
    ".venv/"
    "venv/"
    "env/"
    ""

    "# Temporary files"
    "*.tmp"
    "tmp/"
    "temp/"
    "cache/"
    ".cache/"
    ""

    "# Security and secrets"
    "*.env"
    ".env"
    ".env.*"
    "*.key"
    "*.pem"
    "secrets/"
    "credentials/"
    ""

    "# Custom ignores below"
    "*_old*.*"
    "*_old_*.*"
    "*old_*.*"
    "*-old*.*"
    "*-old-*.*"
    "*old-*.*"
)

GSUBIGNORE_DEFAULTS=("logs" "node_modules" "__pycache__" ".venv" ".DS_Store" ".idea" ".vscode" "plugins" "lib" "docs" "bin" "dist" "build" "tmp" "temp" "cache" ".cache" ".git" "save" "saves" "backups" "backup" "env" "venv" "utils" "utility" "utilities" "scripts")
